### ISSUE TITLE
locoman_utils branch

### ISSUE THREAD

**Issue by dkanou** [robotology-playground/robotology-superbuild#11]
I am trying to sudo update-all, and it keeps pulling the master branch for the locoman_utils, while the walkman_stable in the right one.  Can we fix the Cmake to the stable branch please?  Thanks!

**Comment by liesrock** [comment]
Thanks @dkanou ! I fix the cmake file ( in 14165e5410097d193ee68fb4166ef7181ffc95d0) to clone the stable branch. @alessandrosettimi  and @DaniloCaporale can you please check the dependencies between your packages and fix the related cmake files (like I did it in 2bed4357eb0291b8c27af331ddd7b5887fb7f473) ? There are issues about this in the master branch of the robotology superbuild.

**Comment by liesrock** [comment]
Is it solved?

**Comment by liesrock** [comment]
@DaniloCaporale , @alessandrosettimi we should solve this issue ASAP, can you take care of it?

**Comment by alessandrosettimi** [comment]
I will try to fix it dowloading and compiling a superbuild from scratch and compiling locoman_utils to check that everything is ok... but where is drc_shared? I cannot find it in the new repos.

**Comment by liesrock** [comment]
Hi @alessandrosettimi I just  add you: it's here https://github.com/ADVRHumanoids/DRC_shared

**Comment by alessandrosettimi** [comment]
ok, it should work now!

**Comment by liesrock** [comment]
Ok I trust @alessandrosettimi and I close it!
