### ISSUE TITLE
setting BUILD_COMMAND or INSTALL_COMMAND in the Buildxxx.cmake does not have any effect

### ISSUE THREAD

**Issue by liesrock** [robotology-playground/robotology-superbuild#15]
@drdanz what do you think about this?
me and @alaurenzi would like to jump the BUILD e INSTALL steps for the ADVR_shared repo.
It is easy to reproduce the error:

```
git clone git clone https://github.com/robotology-playground/robotology-superbuild.git -b issue#15 test
cd test && mkdir build 
. robotology-setup.bash
cd build
cmake ..
make ADVR_shared
```

The output will be:

[ 75%] Performing build step for 'ADVR_shared'
[ 87%] Performing install step for 'ADVR_shared'
make[4]: *** No rule to make target `install'.  Stop.
make[3]: *** [configs/ADVR_shared/CMakeFiles/YCMStamp/ADVR_shared-install] Error 2
make[2]: *** [CMakeFiles/ADVR_shared.dir/all] Error 2
make[1]: *** [CMakeFiles/ADVR_shared.dir/rule] Error 2
make: *** [ADVR_shared] Error 2

Here is the BuildADVR_shared.cmake : 

```
# ADVR_shared
include(YCMEPHelper)
include(FindOrBuildPackage)

ycm_ep_helper(  ADVR_shared
                TYPE GIT
                STYLE GITLAB_ADVRCLOUD
                REPOSITORY advr_humanoids/advr_shared.git
                TAG master
                COMPONENT configs
                BUILD_COMMAND ""
                INSTALL_COMMAND ""
            )
```

**Comment by drdanz** [comment]
It might be related to an old issue with `CMakeParseArguments` for which I had a workaround, but that I cannot remember whether I removed it or not.
Which CMake and YCM versions are you using?

**Comment by liesrock** [comment]
We are currently using CMake 3.5 with YCM v0.2.2

**Comment by drdanz** [comment]
@liesrock should be fixed in YCM master, please try changing
YCM_TAG to 538bec08ad3e32b4423fe008e79d0eee941e89e9

**Comment by liesrock** [comment]
Thanks! It works now!

**Comment by drdanz** [comment]
@liesrock Since this is quite an important issue, I will probably release YCM v0.2.3 in the next few days...
