### ISSUE TITLE
Buildbigman-ros.cmake

### ISSUE THREAD

**Issue by dkanou** [robotology-playground/robotology-superbuild#16]
There is an unknown xinsongyan/bigman.git REPO in the master branch that prevents us from compiling. Can we please remove it and switch back to the older version of the cmake for bigman-ros?  Thanks!

**Comment by arocchi** [comment]
I guess it's time adding CI to robotology-superbuild. I started doing so for `OpenSoT`. I would like to set up at least one responsible for project and one responsible for superbuild (COGIMON, CENTAURO, WALKMAN), let's talk about it at next meeting @dkanou @alaurenzi @liesrock @EnricoMingo

**Comment by alaurenzi** [comment]
Isn't it enough to disable it (or to avoid enabling it) from ccmake?

**Comment by liesrock** [comment]
Yes @alaurenzi is right: you should not enable the project if you don't have the permission to read/write.
