### ISSUE TITLE
CMake issue in master branch

### ISSUE THREAD

**Issue by DaniloCaporale** [robotology-playground/robotology-superbuild#17]
cmake gives this error:

 CMake Error at CMakeLists.txt:3 (cmake_policy):
   Policy "CMP0064" is not known to this version of CMake.

This error prevents generating the makefiles. So I commented lines (2-4) in the CMakeLists.txt and tried again. Seems to work like this.

I think the same fix has been applied in a different branch, could it be applied to master branch too?

Thanks for your support.

**Comment by liesrock** [comment]
Hi Danilo, we are trying to have an automatic script that solve the issue by upgrading CMake to 3.5.1 in Ubuntu 14.04.
Check here, there is already a thread about this: https://github.com/robotology-playground/robotology-superbuild/issues/13
