### ISSUE TITLE
What if root access not an option?

### ISSUE THREAD

**Issue by Pouya-moh** [robotology-playground/robotology-superbuild#2]
Hello. 
I would like to install this but I have a big problem. Installing dependencies needs root access which is not granted in our laboratories. Would it possible for you guys to add an entry in the wiki and list all dependencies so we can build from source?

Thanks,
Pouya.

**Comment by liesrock** [comment]
Hello Pouya,
I will work on this as soon as possible.

Best,
Luca

**Comment by liesrock** [comment]
Hello Pouya,
I add in the wiki the list of all robotology superbuild dependencies (for all the repos inside the superbuild).
You can find it here : 
https://github.com/robotology-playground/robotology-superbuild/wiki/robotology-superbuild-handbook#dependencies-list

Neverthless install all the dependencies from sources will be a tough work: I would ask your administrator to run the get_dependencies.sh script in your machine.

Best,
Luca

**Comment by Pouya-moh** [comment]
Thanks a lot Luca. We have many of them already installed so I don't think it would be much of a headache to install all of them. The big headache would be to ask system admins to it for us :D

Thanks again and regards,
Pouya.

**Comment by Pouya-moh** [comment]
Hello Luca.

Thank you very much for detailed list. I checked and it seems we have almost all of them already installed. There are two packages among the missing ones that I have a question about:
1. "icub-common". We are gonna use CoMan only. Do we still need this?
2. "drcsim" It seems this one is relate to darpa challenge, hence, WalkMan. Similar question to above: if we want to use CoMan only, do we need this?

Thank again for the support and cheers,
Pouya.

**Comment by liesrock** [comment]
Hi Pouya,

you will need icub-commn because it has inside some useful libs.
You can skip drcsim.

I am available if you have other questions.
Best,
Luca
