### ISSUE TITLE
Current Gazebo aliases should be added only if GazeboYARPPlugins are installed

### ISSUE THREAD

**Issue by liesrock** [robotology-playground/robotology-superbuild#21]
e.g.
alias gazebo='gazebo -s libgazebo_yarp_clock.so'

**Comment by dkanou** [comment]
Hi @liesrock we need to fix this.  Gazebo aliases in the main bash break the whole simulation when ROS or other middleware is used.  Quick fix to *not* run aliases: > \gazebo

**Comment by liesrock** [comment]
@EnricoMingo I think solved it! Right?

**Comment by dkanou** [comment]
@EnricoMingo just changed the aliases and it is working.  Closing the issue.
