### ISSUE TITLE
Gazebo crashes when linked to iit-bigman-ros-pkg

### ISSUE THREAD

**Issue by alexiatoumpa** [robotology-playground/robotology-superbuild#23]
We have tried with: 1) Gazebo 6.7 and 2) Gazebo 7.6 and with iit-bigman-ros-pkg in master.

Gazebo crashes trying to load the bigman models, i.e.  GAZEBO_MODEL_PATH=~/robotology-superbuild/robots/iit-bigman-ros-pkg/bigman_gazebo/database

If we remove the above path then gazebo starts without of course loading WALK-MAN.

The report of the
> gdb gzclient
is:

visionpc2@visionpc2:~$ gdb gzclient
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gzclient...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/gzclient 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd9047700 (LWP 28224)]
[New Thread 0x7fffd8163700 (LWP 28225)]
[New Thread 0x7fffd7757700 (LWP 28226)]
[New Thread 0x7fffcea7b700 (LWP 28227)]
[New Thread 0x7fffce27a700 (LWP 28228)]
[New Thread 0x7fffcda79700 (LWP 28229)]
[New Thread 0x7fffcd278700 (LWP 28230)]
[New Thread 0x7fffb7189700 (LWP 28231)]
[New Thread 0x7fffb6988700 (LWP 28232)]
[New Thread 0x7fffae8be700 (LWP 28233)]
[New Thread 0x7fffae0bd700 (LWP 28234)]
[New Thread 0x7fffad8bc700 (LWP 28235)]
[New Thread 0x7fff9b9bf700 (LWP 28237)]
[New Thread 0x7fff9b5be700 (LWP 28238)]
[New Thread 0x7fff9b1bd700 (LWP 28239)]
[New Thread 0x7fff9adbc700 (LWP 28240)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff66ae9ea in strlen () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) bt
#0  0x00007ffff66ae9ea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6cbeb24 in std::string::assign(char const*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff772f6bf in gazebo::gui::InsertModelWidget::UpdateLocalPath(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#3  0x00007ffff772fd2c in gazebo::gui::InsertModelWidget::UpdateAllLocalPaths() ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#4  0x00007ffff7730010 in gazebo::gui::InsertModelWidget::InsertModelWidget(QWidget*) ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#5  0x00007ffff774e874 in gazebo::gui::MainWindow::MainWindow() ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#6  0x00007ffff7724fb0 in gazebo::gui::load() () from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#7  0x00007ffff772510c in gazebo::gui::run(int, char**) ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_gui.so.7
#8  0x000000000040152a in ?? ()
#9  0x00007ffff6647f45 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000401614 in _start ()

**Comment by liesrock** [comment]
Solved with c06d2dc111218c76c8371bbdf6b938c206b81e64

**Comment by liesrock** [comment]
```
pip install BeautifulSoup4 lxml 
```
solves the issue: details on the above referenced issue.
