### ISSUE TITLE
trajectory_utils migration

### ISSUE THREAD

**Issue by dkanou** [robotology-playground/robotology-superbuild#25]
Previous REPO: enrico.mingo/trajectory_utils.git
Current REPO: ADVRHumanoids/trajectory_utils.git

Though current REPO does not exist.

**Comment by liesrock** [comment]
Hi @dkanou , the responsible for the repo is @EnricoMingo and this repo was in its own namespace: I ask in the advr_software mailing list to inform me of this kind of repo to migrate, but I did not receive anything about the trajectory_utils repo, so I did not migrate it.
Neverthless I had a local copy and I push it here: https://github.com/ADVRHumanoids/trajectory_utils

So the problem should be solved.

Moreover I have a backup of all the repo in the old gitlab.robotology.eu server: @EnricoMingo please check if commits are missing in the current repo.
