### ISSUE TITLE
write a better README

### ISSUE THREAD

**Issue by arocchi** [robotology-playground/robotology-superbuild#3]
...maybe taking a generic description from the WIKI?

**Comment by liesrock** [comment]
I agree with you....what do you mean exactly? Do you have any suggestion?

**Comment by arocchi** [comment]
Brainstorming v0.0:

The robotology-superbuild is a project that aims at easing the installation and maintenance of the software stack developed at IIT for the control of humanoid robots.

...

**Comment by liesrock** [comment]
I did some work about this: I will need also @EnricoMingo and @alaurenzi help.
