### ISSUE TITLE
switch default gazebo to gazebo6

### ISSUE THREAD

**Issue by arocchi** [robotology-playground/robotology-superbuild#6]
We should test that everything works when doing a fresh install.
Also, we should test all functionalities are preserved, including sensors. Maybe Dimitri could take care of testing.
@liesrock @EnricoMingo, what do you guys think?

**Comment by liesrock** [comment]
Hi @arocchi ,
from the Gazebo-YARP plugin point of view we should not have any problems ( @traversaro can confirm).
What do @dkanou and @EnricoMingo think about the sensors ?

**Comment by dkanou** [comment]
Hi @liesrock, @EnricoMingo, and @arocchi --

my problem is that Mutlisense-SL plugin is now at a different brunch (simulation) and I am not sure if it will ever be part of the Master brunch since there is code hardcoded for ATLAS.  Are we planning to fix these before doing anything else?

**Comment by liesrock** [comment]
@EnricoMingo  what do you think about this?

**Comment by traversaro** [comment]
@liesrock no problems on `gazebo-yarp-plugins` related to Gazebo 6 in particular as far as I know. We try to stick with Gazebo 7 at the moment, but until the last year we used Gazebo 6 with no problems.

**Comment by liesrock** [comment]
Thanks @traversaro!

**Comment by EnricoMingo** [comment]
We can keep the multisense branch updated merging the master on it once in
a while. Not sure if the vice-versa is possible...

2016-05-09 9:54 GMT+02:00 Luca Muratore notifications@github.com:

> Thanks @traversaro https://github.com/traversaro!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/robotology-playground/robotology-superbuild/issues/6#issuecomment-217798852

## 

Ing. Mingo Enrico Hoffman
Istituto Italiano di Tecnologia, Genova

**Comment by dkanou** [comment]
Do you think that there is anyone (PhD/Intern) that could work on removing the ATLAS hardcoded pieces and adapt the code to WALK-MAN?  This could help us from doing these merges.

**Comment by EnricoMingo** [comment]
Yes...but this is that kind of work that no one would like to do you know...

2016-05-09 13:53 GMT+02:00 Dimitrios Kanoulas notifications@github.com:

> Do you think that there is anyone (PhD/Intern) that could work on removing
> the ATLAS hardcoded pieces and adapt the code to WALK-MAN? This could help
> us from doing these merges.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/robotology-playground/robotology-superbuild/issues/6#issuecomment-217844323

## 

Ing. Mingo Enrico Hoffman
Istituto Italiano di Tecnologia, Genova

**Comment by dkanou** [comment]
Let me see if there is any chance to have a PhD/Intern working on that.  I believe that as long as things are ATLAS hard coded in the plugin and thus not being able to include the feature in the master branch it would be always a pain in the ass to integrate and use vision in Gazebo.  I will get back to you when I find such a person.  I believe that it is a 2 weeks task.  What do you think?

**Comment by liesrock** [comment]
@dkanou do we have any news about this?

**Comment by liesrock** [comment]
We fix the versione to 7.5 on basic_setup
