### ISSUE TITLE
Dependencies of walking module

### ISSUE THREAD

**Issue by krprzemo** [robotology-playground/robotology-superbuild#9]
It would be nice to have a singe keyword for walking in cmake that would enable all dependencies. Adding the following in CMake doesn't do the job:  
`set(SUPERBUILD_walking2 OFF CACHE BOOL "Flag to compile walking module and dependencies")`
`SUPERBUILD_walking2)`
`find_or_build_package_with_tag(walking ON)`
`find_or_build_package_with_tag(arms_ik ON)`
`find_or_build_package_with_tag(locoman_utils ON)`
`ENDIF(SUPERBUILD_walking2)`
doesn't enable the dependent packages

**Comment by liesrock** [comment]
@duncanjovial: it is solve.
